// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sstzbgdulvizfsuzorwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzdHpiZ2R1bHZpemZzdXpvcndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzI1NjksImV4cCI6MjA3Mjg0ODU2OX0.Sox9a4879yslC28JB0pr2YLYUxrTMpFSfc-mg_M1_I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});